version: '3'
services:
  python-app:
    container_name: python-scanner-excel
    build:
      context: ./questionScanner
    ports:
      - "8010:8010"
    restart: always
  postgres:
    container_name: first-db
    image: "postgres:15"
    restart: always
    ports:
      - "5434:5434"
    environment:
      POSTGRES_DB: educationtest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: omonov2006
  spring-app:
    container_name: spring-education-test
    build:
      context: ./EDUCATIONTEST
    restart: always
    ports:
      - "8088:8088"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://first-db:5432/educationtest
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: omonov2006