version: '3'
services:
  python-app:
    container_name: python-scanner-excel
    build:
      context: ./questionScanner
    ports:
      - "8010:8010"
    restart: always

  spring-app:
    container_name: spring-education-test
    build:
      context: ./EDUCATIONTEST
    restart: always
    ports:
      - "8088:8088"
