spring:
  sql:
    init:
      mode: always
  servlet:
    multipart:
      enabled: true
      max-request-size: 215MB
      max-file-size: 215MB
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8088
  error:
    include-message: always
fast:
  url: http://python-scanner-excel:8010/